=== yuferovalex/xslt/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cv">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="firstName" />
        <xs:element minOccurs="0" maxOccurs="1" ref="middleName" />
        <xs:element ref="lastName" />
        <xs:element ref="birthdate" />
        <xs:element ref="sex" />
        <xs:element ref="status" />
        <xs:element minOccurs="0" maxOccurs="1" ref="photo" />
        <xs:element ref="address" />
        <xs:element ref="contacts" />
        <xs:element ref="objective" />
        <xs:element minOccurs="0" maxOccurs="1" ref="experience" />
        <xs:element minOccurs="0" maxOccurs="1" ref="educations" />
        <xs:element minOccurs="0" maxOccurs="1" ref="languages" />
        <xs:element ref="skills" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="firstName" type="xs:string" />
  <xs:element name="middleName" type="xs:string" />
  <xs:element name="lastName" type="xs:string" />
  <xs:element name="birthdate" type="xs:string" />
  <xs:element name="sex" type="xs:string" />
  <xs:element name="status" type="xs:string" />
  
  <xs:element name="photo">
    <xs:complexType>
      <xs:attribute name="href" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="country" />
        <xs:element ref="district" />
        <xs:element ref="city" />
        <xs:element ref="street" />
        <xs:element ref="house" />
        <xs:element ref="flat" />
        <xs:element minOccurs="0" maxOccurs="1" ref="zip" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="country" type="xs:string" />
  <xs:element name="district" type="xs:string" />
  <xs:element name="city" type="xs:string" />
  <xs:element name="street" type="xs:string" />
  <xs:element name="house" type="xs:string" />
  <xs:element name="flat" type="xs:string" />
  <xs:element name="zip" type="xs:string" />
  
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="phone" />
        <xs:element minOccurs="0" maxOccurs="1" ref="email" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="smedia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="phone" type="xs:string" />
  <xs:element name="email" type="xs:string" />
  <xs:element name="smedia" type="xs:string" />
  
  <xs:element name="objective">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="position" />
        <xs:element minOccurs="0" maxOccurs="1" ref="salary" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="position" type="xs:string" />
  <xs:element name="salary" type="xs:string" />
  
  <xs:element name="experience">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="case" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="case">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="position" />
        <xs:element ref="company" />
      </xs:sequence>
      <xs:attribute name="from" type="xs:string" use="required" />
      <xs:attribute name="to" type="xs:string" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="company" type="xs:string" />
  
  <xs:element name="educations">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="education" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="education">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="institution" />
        <xs:element ref="program" />
      </xs:sequence>
      <xs:attribute name="from" type="xs:string" use="required" />
      <xs:attribute name="to" type="xs:string" />
      <xs:attribute name="type" type="xs:NMTOKEN" use="required" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="institution" type="xs:string" />
  <xs:element name="environment" type="xs:string" />
  <xs:element name="system" type="xs:string" />
  <xs:element name="platform" type="xs:string" />
  <xs:element name="language" type="xs:string" />
  
  <xs:element name="program">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="code" type="xs:NMTOKEN" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="languages">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="language" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="skills">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="environments" />
        <xs:element minOccurs="0" maxOccurs="1" ref="systems" />
        <xs:element minOccurs="0" maxOccurs="1" ref="platforms" />
        <xs:element minOccurs="0" maxOccurs="1" ref="programmingLanguages" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="environments">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="environment" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="systems">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="system" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="platforms">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="platform" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="programmingLanguages">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="language" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yuferovalex/xslt/Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="svg.xsl"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="schema.xsd">
    <firstName>Александр</firstName>
    <middleName>Владимирович</middleName>
    <lastName>Юферов</lastName>
    <birthdate>16.12.1995</birthdate>
    <sex>Male</sex>
    <status>Single</status>
    <photo href="https://previews.123rf.com/images/grgroup/grgroup1707/grgroup170700124/81412228-colorful-silhouette-of-man-face-with-red-hair-and-beard-vector-illustration.jpg" />
    
    <address>
        <country>Россия</country>
        <district>Челябинская обл.</district>
        <city>Челябинск</city>
        <street>Елькина</street>
        <house>55</house>
        <flat>44</flat>
        <zip>454091</zip>
    </address>
    
    <contacts>
        <phone>+73512000000</phone>
        <email>operator@localhost</email>
        <smedia>https://github.com/yuferovalex</smedia>
        <smedia>https://vk.com/yuferov_alex</smedia>
    </contacts>
    
    <objective>
        <position>Младший инженер-разработчик</position>
        <salary>40000</salary>
    </objective>
    
    <experience>
        <case from="01.2018" to="02.2019">
            <position>Программист-стажер</position>
            <company>ООО Вектор</company>
        </case>
        <case from="02.2019">
            <position>Ни кем</position>
            <company>Ни где</company>
        </case>
    </experience>
    
    <educations>
        <education type="bachelor" from="2014" to="2018">
            <institution>South Ural State University</institution>
            <program code="09.03.04">Software Engenering</program>
        </education>
        <education type="master" from="2018" to="2020">
            <institution>South Ural State University</institution>
            <program code="00.00.00">Some Program</program>
        </education>
      <education type="master" from="2003" to="2011">
        <institution>School</institution>
        <program code="00.00.00">Some Program</program>
      </education>
    </educations>

    <languages>
        <language>English</language>
        <language>Lingua Latina</language>
    </languages>

    <skills>
        <environments>
            <environment>Builder C++</environment>
            <environment>IntelliJ IDEA</environment>
        </environments>
        <systems>
            <system>Windows</system>
            <system>CentOS</system>
        </systems>
        <platforms>
            <platform>x86</platform>
            <platform>ARM</platform>
            <platform>Alpha</platform>
        </platforms>
        <programmingLanguages>
            <language>C++</language>
            <language>Java</language>
        </programmingLanguages>
    </skills>
</cv>
